title: Dayda
name: Cook County of Illinois
description: >-
  This is a catalog of datasets organized and made more accessible from Cook
  County of Illinois, providing simple dowloadable CSV and JSON files, as well
  as Postman Collections you can use as part of workflows and other automation.
about: This is all about the entity.
source_url: 'http://example.com'
source_contact_type: general
source_phone: +1 555-555-5555
source_email: info@example.com
source_catalog: data.gov
profile_pic: 'https://legacy.cookcountyil.gov/secretary/CookColorSeal.jpg'
favicon: /assets/img/favicon.png
url: 'http://cook-county-of-illinois.dayda.org'
encoding: utf-8
paginate: 25
paginate_path: '/page:num/'
markdown: kramdown
